name: Deploy Node.js Application to Development Server

on:
  push:
    branches:
      - develop  # Adjust this as necessary for your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Adjust this to your project's Node.js version

    - name: Install npm dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Rsync files over SSH using sshpass
      run: |
        sshpass -p ${{ secrets.PASSWORD }} rsync -avz --delete ./build/ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/usr/share/nginx/html/
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
